### ISSUE TITLE
Bootstrap project

### ISSUE THREAD

**Issue by om26er** [xconnio/wampproto.rb#12]
Must be the first work item.

* Create a ruby project
* Add linting
* Add github action for CI

**Comment by rubyonrails3** [comment]
@om26er  this is done, BTW when do we close an issue?

**Comment by rubyonrails3** [comment]
closes: https://github.com/xconnio/wampproto.rb/pull/16

**Comment by om26er** [comment]
fixed via https://github.com/xconnio/wampproto.rb/pull/16
